version: "3.7"

services:
  apache:
    build:
      context: ./apache
      dockerfile: Dockerfile
    restart: on-failure
    links:
      - mysql
    volumes:
      - ./apache/src:/var/www/html
    ports:
      - "8080:8080"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: on-failure
    links:
      - mysql
    volumes:
      - ./nginx/src:/usr/share/nginx/html-static
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8081:8081"

  mysql:
    image: mysql:8.0.30
    restart: on-failure
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: appDB
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d

  redis:
    image: redis:6.2.7
    command: redis-server
    restart: on-failure
    ports:
      - "6379:6379"

  phpmyadmin:
    image: phpmyadmin:5.2.0
    restart: on-failure
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "5000:5000"
      